name: Ruby Script Runner

on:
  push:
    branches:
      - main

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1

      - name: Install Bundler
        run: gem install bundler

      - name: Install Dependencies
        run: |
          if [ -f Gemfile ]; then
            bundle install
          else
            echo "Gemfile not found"
            exit 1
          fi

      - name: Run Ruby script
        run: ruby bookshallucinated.rb
