name: Run Until Complete

on:
  workflow_dispatch: # Allows manual trigger of the workflow

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Run the Script
        run: ruby your_script.rb

      - name: Upload Output File
        uses: actions/upload-artifact@v3
        with:
          name: output-file
          path: ./history_geo.json # Assuming file.json is generated in the root directory of the repository
