name: Run Ruby Script and Save Output

on:
  push:
    branches:
      - main

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1

      - name: Install Dependencies
        run: |
          gem install bundler
          bundle install

      - name: Run Ruby script
        run: ruby bookshallucinated.rb

      - name: Upload Generated File
        uses: actions/upload-artifact@v3
        with:
          name: generated-file
          path:   tabkh.json
