name: Ruby Capybara Workflow

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2' # Specify your Ruby version

      - name: Download checkpoint
        uses: actions/download-artifact@v4
        with:
          name: checkpoint
          path: . # Save in the current directory

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install

      - name: Run script
        run: |
          ruby your_script.rb

      - name: Upload JSON file
        uses: actions/upload-artifact@v4
        with:
          name: output-json
          path: output.json # Adjust the path as necessary

      - name: Upload checkpoint
        uses: actions/upload-artifact@v4
        with:
          name: checkpoint
          path: checkpoint.json
