name: Run Until Complete

on:
  workflow_dispatch: 
jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Run the Script
        run: ruby bookshallucinated.rb

      - name: Upload Output File
        uses: actions/upload-artifact@v3
        with:
          name: output-file
          path: file.json 
