name: Ruby Capybara Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2' # Specify your Ruby version

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install

      - name: Run script
        run: |
          ruby your_script.rb

      - name: Upload JSON file
        uses: actions/upload-artifact@v3
        with:
          name: output-json
          path: output.json # Change this to the path of your generated JSON file
